### ISSUE TITLE
Plugin Timezone Issue

### ISSUE THREAD

**Issue by erickbatista** [keydet89/RegRipper2.8#10]
Hello

I'm having some problems with "timezone.pl" plugin. RegRipper is not parsing the information on "TimeZoneKeyName" key. 

When I googled about this issue I found this site "http://resources.infosecinstitute.com/registry-forensics-regripper-command-line-linux/", on "Determining the time zone" section, the printscreen shows information about that key.

Below you can see the results of the parsing. I've tested it on two SYSTEM hives.

---

timezone v.20080324
(System) Get TimeZoneInformation key contents

TimeZoneInformation key
ControlSet001\Control\TimeZoneInformation
LastWrite Time Mon Oct 19 11:01:48 2015 (UTC)
  DaylightName   -> @tzres.dll,-41
  StandardName   -> @tzres.dll,-42
  Bias           -> 180 (3 hours)
##   ActiveTimeBias -> 120 (2 hours)

Best Regards,

Erick

**Comment by keydet89** [comment]
Erick,

Have you confirmed that the hives you're process have a "TimeZoneKeyName" value?

Thanks.

**Comment by erickbatista** [comment]
Hello,

Yes, the hives that I'm using have a "TimeZoneKeyName" value.

Do you need any additional information about the key or about the hives that I'm using?

Best Regards,

Erick

**Comment by keydet89** [comment]
Could you send me an example System hive at keydet89 at yahoo dot com?

**Comment by erickbatista** [comment]
I sent to your email box.

Thanks.

**Comment by zpravaiz** [comment]
I too see incorrect value. My timezone is +4 Asisa/Dubai but it shows -4 


ControlSet001\Control\TimeZoneInformation
LastWrite Time Sun Jun 28 22:21:11 2015 (UTC)
  DaylightName   -> @tzres.dll,-441
  StandardName   -> @tzres.dll,-442
  Bias           -> -240 (-4 hours)
  ActiveTimeBias -> -240 (-4 hours)
  TimeZoneKeyName-> Arabian Standard Time

**Comment by keydet89** [comment]
Can you provide sample data to test?  Thanks.

**Comment by zpravaiz** [comment]
Hi,

Please find the hive attached.

Thanks

**Comment by keydet89** [comment]
I'm not seeing any attachments...
