### ISSUE TITLE
Feature Request - Parsing Multiple Controlsets

### ISSUE THREAD

**Issue by duckexmachina** [keydet89/RegRipper2.8#11]
Hey Harlan. Just had a case where log2timeline was turning up relevant events from the appcompatcache that Initially I could not validate with regripper (log indicates appcompatcache.pl v20150611 though the comments show 20160217). 
Digging into the plugin, it looks as though it only parses the "select" control set. I had to hand-jam it to run against another control set. I would request adding a loop to parse all extant control sets, not just for this plugin, but perhaps for all...

**Comment by keydet89** [comment]
I don't think I'd have to add a loop, per se, as the code uses a loop to determine the controlset that is marked as "current".  

So, you're asking to potentially have a significant amount of data added to the output...you're aware of that?  I've seen server systems with three control sets, and parsing the data you're asking for would provide a great deal of extra data.

**Comment by duckexmachina** [comment]
Exactly

**Comment by keydet89** [comment]
So, for all plugins that check the System hive, or just AppCompatCache?

**Comment by keydet89** [comment]
I've written a version of the appcompatcache.pl plugin called "shimcache.pl", that collects the shimcache entries from all available ControlSets.  I don't see that doing the same for every key checked in the System hive is necessary or appropriate, although I would be happy to entertain comments to the contrary.

**Comment by duckexmachina** [comment]
Thanks, Harlan. To date. I haven't had any specific need  for that. I agree it may not be necessary.
I appreciate you taking the time to enhance this plugin... I didn't know what I was missing...

**Comment by keydet89** [comment]
I've updated the plugin and will upload it to the distro.  The data I've run it against, however, has been duplicate entries in both ControlSets.
