### ISSUE TITLE
SAM User Login info doesn't include Microsoft Account based authentications

### ISSUE THREAD

**Issue by gregfreemyer** [keydet89/RegRipper2.8#14]
I don't know if this is a bug.  And if so, is it best addressed with a warning in the output?  Or can it actually be fixed?

== Situation

I'm looking at the security event log from a system.  The user logged into the system using a local account for the first part of 2015.  Then they started logging in using a Microsoft Account.

From what I see the profile (C:\Users\JohnDoe) was maintained when the switch was made so from all practical purposes the user was using the same account before and after the switch.

Using RegRipper pulled from git on May 7, 2016 I see a misleading report if I run:

rr.exe
- select SAM hive and SAM profile
- run report

It shows me the last login date was the date of the switch, not the last time the user authenticated with the Microsoft Account.

At a minimum a note the info reflects only local account authentications and not Windows Account authentications would be appropriate.

Best would be to have 2 entries.  One for the last login for each of the 2 methodologies.

**Comment by keydet89** [comment]
I'm not clear what you're asking for here...could you elaborate, and if possible, provide sample data?

**Comment by gregfreemyer** [comment]
Historically users had 2 ways to login to a computer:  local account and domain account.  Each of those maintained a separate profile, thus for all intents and purposes the 2 login methods represented 2 separate logical users.

As of Windows 8, there are now 3 ways for a user to log into a Windows system:

- local account credentials
- Microsoft account credentials
- Domain account credentials.

As I understand it, logging in via either the Local Account Credentials or the Microsoft Account credentials the same profile is used (/Users/JohnDoe), so they are simple 2 alternate ways of logging into the same account.

This is a sample portion of the SAM Identities report where the user first logged in via the local credentials for several months, then began using the Microsoft credentials for the last 6 months of the computers usage::

======================
Username        : <redacted>[1001]
Full Name       : <redacted>
User Comment    : 
Account Type    : Default Admin User
Account Created : Mon Mar 30 06:19:29 2015 Z
Name            : <redacted>
InternetName    : <redacted>@outlook.com
Password Hint   : common
Last Login Date : Thu May 21 05:27:03 2015 Z
Pwd Reset Date  : Thu Nov 12 13:17:05 2015 Z
Pwd Fail Date   : Thu May 21 05:25:45 2015 Z
Login Count     : 46
==================================

Based on the above, one would conclude the last time the account was logged into would be May 2015.  In actuality it was Nov 24th, 2015.

Thus the above is not accurate.  By reviewing the security log I found numerous logins between May 2015 and Nov 2015.  May 2015 was the last time the user authenticated via local credentials (username / password).

From May 2015 to Nov 24, 2015, the user authenticated via their Microsoft account <redacted>@outlook.com.

At a minimum this line

Last Login Date : Thu May 21 05:27:03 2015 Z

should be changed to read:

Last Login via machine local account credentials: Date : Thu May 21 05:27:03 2015 Z
Note that prior line does not reflect account logins using Microsoft account credentials.
===

I'm afraid I can't share the SAM registry with you.  It may not be that hard to recreate a similar situation.

Thanks
Greg

**Comment by keydet89** [comment]
Okay, so instead of making and submitting the change, you just want me to go in and change the wording of a one of the output lines?

**Comment by keydet89** [comment]
I think that the issue here is a basic understanding of the different types of accounts available.  I think that most analysts are familiar with the local and domain accounts, and the Microsoft (Live) account is simply something new:

http://www.top-password.com/blog/the-secrets-of-windows-8-microsoft-account/
http://justaskweg.com/?p=1408
