### ISSUE TITLE
prefetch plugin error

### ISSUE THREAD

**Issue by zpravaiz** [keydet89/RegRipper2.8#15]
When i try to run prefetch  plugin i get following error.

Launching prefetch v.20120914
prefetch v.20120914
(SYSTEM) Gets the the Prefetch Parameters

Error in plugins/prefetch.pl: Can't call method "get_data" on an undefined value at plugins/prefetch.pl line 55.

Help appreciated

**Comment by keydet89** [comment]
Can you provide the command line you used, as well as sample data?  Thanks.

**Comment by zpravaiz** [comment]
Hi,

Please find it below. and attached the SYSTEM hive.



root@siftworkstation:~/RegRipper2.8# perl rip.pl  -r
/cases/callbillin02/SYSTEM -p prefetch

Launching prefetch v.20120914
prefetch v.20120914
(SYSTEM) Gets the the Prefetch Parameters

Error in plugins/prefetch.pl: Can't call method "get_data" on an undefined
value at plugins/prefetch.pl line 55.

**Comment by keydet89** [comment]
Sorry, no System hive came through.

**Comment by zpravaiz** [comment]
Strange. I am attaching and sending dropbox link too. Same hive for other
issue too for timezone.



https://www.dropbox.com/s/01622iqkcg5gn28/SYSTEM?dl=0

**Comment by keydet89** [comment]
Okay, I have to create an account to get access to this...

**Comment by keydet89** [comment]
I was able to download the System hive file you provided.  I opened it in a viewer and quickly found out the reason for the error...there is no EnablePrefetcher value beneath the key.  

I'm closing this issue.

**Comment by zpravaiz** [comment]
Thank you very much for looking into this. Error msg was confusing which
looks like a bug.

Cheer
