### ISSUE TITLE
Feature Request (new plugin, or mod to services): Extract Application, AppDirectory, & AppParameters for services using srvany.exe

### ISSUE THREAD

**Issue by johnmccash** [keydet89/RegRipper2.8#25]
Hey Harlan,
I just ran across a use case that the current services plugin for regripper doesn't adequately cover. There's an old tool, first made available in the NT 4.0 Resource kit, called srvany.exe, that runs normal applications as services. When a service is installed this way, the service extraction done by the current plugin just shows the path of srvany.exe. It would probably be worthwhile to add a new srvany plugin (or modify the current services plugin) to parse out the “HKLM\System\CurrentControlSet\Services\<service name>\Parameters\Application”, “HKLM\System\CurrentControlSet\Services\<service name>\Parameters\AppDirectory”, and “HKLM\System\CurrentControlSet\Services\<service name>\Parameters\AppParameters” values that srvany uses to hold its config information.

**Comment by randomaccess3** [comment]
I would suggest emailing Harlan directly at keydet89 at yahoo dot com with your description and sample hive. He's generally very responsive via email

**Comment by keydet89** [comment]
John,

Sorry I'm just seeing this...I'm not a developer by profession and have had some trouble getting used to Github.  

Can you provide some sample data?  

Thanks.

**Comment by johnmccash** [comment]
I'm kinda swamped this week. Will try and get something put together, maybe next week.
John

**Comment by keydet89** [comment]
John,

I'm guessing this one just got away from you....

**Comment by johnmccash** [comment]
I suck... And I'm even busier now than when I submitted this. <sigh>

Here are some values I just pulled:
“HKLM\System\CurrentControlSet\Services<service name>\Parameters\Application”:
Application    REG_SZ    E:\DATA\FOLDERNAME\EXENAME.EXE
“HKLM\System\CurrentControlSet\Services<service name>\Parameters\AppDirectory”:
Not set on anything I currently see, but I would assume REG_SZ, containing a simple folder path
“HKLM\System\CurrentControlSet\Services<service name>\Parameters\AppParameters”: 
AppParameters    REG_SZ    /NOUI
