### ISSUE TITLE
Integrate MISP & RegRipper

### ISSUE THREAD

**Issue by elhoim** [keydet89/RegRipper2.8#3]
[MISP (Malware Information Sharing Platform)](https://github.com/MISP/MISP) is a platform to exchange technical IOCs. Some of the data types stored in MISP events are registry keys and registry keys + values.

It would be great to have a plugin for regripper that can parse one of the output formats of MISP dumps (json, XML or CSV) for data and then output a report of matching items.

https://github.com/MISP/MISP/issues/471 has been created to coordinate interaction & integration.

I can provide access to a very active MISP community or give you a dump in the format of your choice.

I am requesting this since i think there is a bit of a "chicken and egg" situation. Lots of data added to MISP communities is not registry keys which are very good artifacts probably because there is not easy way to leverage it from MISP (so far). If there was such a plugin, this would definitely help to make the case for storing and sharing registry keys IOCs in MISP.

**Comment by keydet89** [comment]
David,
I'm sure I could write something to parse the MISP IOCs.  I know that Perl handles json and XML just fine...do you have examples available?  I went to the site and didn't see any plugins available. ------------------------------------------
Harlan Carvey
"Windows Forensic Analysis"
http://windowsir.blogspot.com
------------------------------------------
