### ISSUE TITLE
Using RegRipper on Linux (docker)

### ISSUE THREAD

**Issue by ilyaglow** [keydet89/RegRipper2.8#30]
There are [few](https://linuxconfig.org/how-to-install-regripper-registry-data-extraction-tool-on-linux) [guides](http://www.thegreycorner.com/2010/04/running-regripper-on-linux.html) to [do](http://resources.infosecinstitute.com/registry-forensics-regripper-command-line-linux/) this, but they are really outdated and not relevant anymore.

I'm not a perl guy to be honest and I hope someone will show me the way I can use this tool on Linux.

I made a Dockerfile to simplify testing:

```shell
FROM alpine

RUN apk update \
  && apk add perl \
  && apk add --virtual .temp \
             perl-dev \
             make \
             git \
             wget \
             \
  && wget https://cpanmin.us/ -O /bin/cpanm \
  && chmod +x /bin/cpanm \
  && cpanm Parse::Win32Registry

RUN git clone --branch=master \
              --depth=1 \
              https://github.com/keydet89/RegRipper2.8.git /regripper

WORKDIR /regripper
CMD ash
```

Dispite the fact that `perl rip.pl -l` works, `perl.rip.pl -f plugin -r hive` does not, and gives me an error:

```
/regripper # perl rip.pl -f winver -r some
Parsed Plugins file.
Error in : Can't locate plugins/.pl in @INC (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at rip.pl line 132.

 complete.
----------------------------------------
```

I tried to change `$pluginsdir` path to an absolute path like `/regripper/plugins` but it didn't work (almost same error)

Tried to use plugin name with `.pl` ending in ex. `perl rip.pl -f winver.pl -r file` but it throws lots of error lines with plugin's source code:
```
/regripper # perl rip.pl -f winver.pl -r some
Parsed Plugins file.
Error in package winver;: Can't locate plugins/package winver;.pl in @INC (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at rip.pl line 132.

package winver; complete.
----------------------------------------
Error in use strict;: Can't locate plugins/use strict;.pl in @INC (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at rip.pl line 132.

use strict; complete.
----------------------------------------
Error in my %config = (hive          => "Software",: Can't locate plugins/my %config = (hive          => "Software",.pl in @INC (@INC contains: /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at rip.pl line 132.

my %config = (hive          => "Software", complete.
...
```

Any help is appreciated!

**Comment by randomaccess3** [comment]
Hi
I think your issue is syntax.

You're trying to run a profile. These are files that contain many plugins and have no file extension

for example: perl rip.pl -f ntuser -r "NTUSER.DAT"
will run every ntuser plugin in the ntuser profile file

My preference is to run the plugin that I'm after
so 
perl rip.pl -p <plugin> -r <reg file>
The plugin that you want to run is in the plugins directory, and you just remove the extension to run it.

To run the plugin you tried you should run the following:
C:\regripper>rip.pl -p winver -r software

**Comment by ilyaglow** [comment]
Woah, how could I missed that, thanks @randomaccess3

**Comment by ilyaglow** [comment]
if somebody interested I finally made a [docker for regripper](https://github.com/ilyaglow/docker-regripper). Don't know is it worth it for a pull request though.
