### ISSUE TITLE
Add regripper plugin for the ‘bam’ registry key (full path and the last execution time)

### ISSUE THREAD

**Issue by Karneades** [keydet89/RegRipper2.8#36]
According to some current blog posts - [https://padawan-4n6.hatenablog.com/entry/2018/02/22/131110](https://padawan-4n6.hatenablog.com/entry/2018/02/22/131110)
and [http://port139.hatenablog.com/entry/2018/02/24/083023](http://port139.hatenablog.com/entry/2018/02/24/083023), there is the following registry key called "bam" which stores program executions - path and timestamp:
`HKLM/SYSTEM/CurrentControlSet/Services/bam/UserSettings/{SID-RID}`

From one of those blog posts:

> Kasasagi at ‘Apprentice forensic ‘s note’ has identified the ‘bam’ key in the Windows registry that stores the full path of an executable and the last execution time. It is indicated that this is only written when the computer is shut down so checking the registry on a live system may not be accurate (without parsing memory).

I created this issue as a placeholder, unfortunately, I do not have test data available. It would be great to add a plugin for this registry key to regripper. However, on my test machines I didn't found this key - could be that Windows 10 ver 1709 is needed for that (as I found this version number in one of those blog posts. Maybe someone could provide an example for Harlan, because, as always, he's only able to write such a plugin with some test data available (as written again and again in his blog posts) :)

**Comment by randomaccess3** [comment]
Already in progress, spoke with Harlan about it last week and he said he was working on a plugin for bam and dam

(also i recognise that blog you quoted ha)

**Comment by Karneades** [comment]
Thanks for the info regarding the plugin.

> (also i recognise that blog you quoted ha)

Of course you do ;) Fixed the issue text because I mixed up the quote and the corresponding blog post.

FTR #2 One more blog post about bam: http://port139.hatenablog.com/entry/2018/03/03/110202
