### ISSUE TITLE
get_root_key error when using system, software etc hive files

### ISSUE THREAD

**Issue by cybgit** [keydet89/RegRipper2.8#38]
Firstly, kudos for this tool.

Appreciate this issue was closed previously, but i'm having the same issue trying to run this against .reg files exported. It works with NTUSER.DAT file no problem, but whenever i try and run against a HIVE file i get the same error on any plugin:

Two example export and running below.

C:\Utils\RegRipper2.8-master>reg export HKEY_LOCAL_MACHINE HKLM
The operation completed successfully.

C:\Utils\RegRipper2.8-master>rip.exe -r HKLM -p appcompatcache
Launching appcompatcache v.20180311
appcompatcache v.20180311
(System) Parse files from System hive AppCompatCache

Error in plugins\appcompatcache.pl: Can't call method "get_root_key" on an undefined value at C:\Utils\RegRipper2.8-master/plugins\appcompatcache.pl line 68.

C:\Utils\RegRipper2.8-master>reg export HKEY_LOCAL_MACHINE\SYSTEM HKLM_SYSTEM.reg
The operation completed successfully.

C:\Utils\RegRipper2.8-master>rip.exe -r HKLM_SYSTEM.reg -p appcompatcache
Launching appcompatcache v.20180311
appcompatcache v.20180311
(System) Parse files from System hive AppCompatCache

Error in plugins\appcompatcache.pl: Can't call method "get_root_key" on an undefined value at C:\Utils\RegRipper2.8-master/plugins\appcompatcache.pl line 68.

I wonder if the Parse::Win32Registry was not included in the rr.exe? Would that cause this?

Rgds

**Comment by randomaccess3** [comment]
extracting the registry using the reg export command results in a different format to the actual hives, so it wont work.

Use something like ftkimager to get access to the system hive and then extract it and process with regripper

**Comment by cybgit** [comment]
Arrr that makes sense. Thank you. 
I also tried pointing it to files in %windir%\system32\config such as SYSTEM but there is access issues on a running system i believe, hence the need for imaging.

**Comment by cybgit** [comment]
Just an update in case this helps anyone else. If you want to create a hive file on a running system in binary format to view with regripper use reg save instead of reg export.

reg save HKLM\SYSTEM hive-system 

you can then rip with

rip.exe -r hive.system -f system
