### ISSUE TITLE
Fix licensing

### ISSUE THREAD

**Issue by joachimmetz** [keydet89/RegRipper2.8#4]
[License](https://github.com/keydet89/RegRipper2.8/blob/master/license.txt) does not comply with GPL v2 guidelines 

Please read:
- https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html
- https://www.gnu.org/licenses/gpl-howto.html

You should also include

> - a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs the license is usually in a file called COPYING.

And from: https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#GPLOmitPreamble

> The preamble and instructions are integral parts of the GNU GPL and may not be omitted. In fact, the GPL is copyrighted, and its license permits only verbatim copying of the entire GPL. (You can use the legal terms to make another license but it won't be the GNU GPL.)

**Comment by keydet89** [comment]
Thanks for your input, I think I got it all.

**Comment by joachimmetz** [comment]
Seeing you don't have a contributors agreement. You cannot change your license without approval from all your contributors.

E.g. https://github.com/keydet89/RegRipper2.8/commits/master/plugins/shellbags_xp.pl where is the OK from the contributor for that license change.

**Comment by joachimmetz** [comment]
The only proper way to fix this is:

* revert to the original license(s)
* fix the issues of the project not complying to the license(s)
* create a PR to change the license(s) to MIT
* have all of the contributors OK the PR

**Comment by joachimmetz** [comment]
https://opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project
