### ISSUE TITLE
Can't locate plugins\samparse_ltn.pl in @INC

### ISSUE THREAD

**Issue by dfirnewbie** [keydet89/RegRipper2.8#51]
I'm trying to run RegRipper against a SAM file, but when parsing it, the following error was returned:

```
Tue May 21 14:02:45 2019: Error in samparse_ltn: 
PLEASE SEE THE PERL2EXE USER MANUAL UNDER "Can't locate somemodule.pm in @INC"
FOR AN EXPLANATION OF THE FOLLOWING MESSAGE:
Can't locate plugins\samparse_ltn.pl in @INC (@INC contains: PERL2EXE_STORAGE C:\Users\<redacted username>\Desktop\Tools\RegRipper C:\Users\<redacted username>\AppData\Local\Temp/p2xtmp-14664) at C:\Users\<redacted username>\Desktop\Tools\RegRipper\rr.exe line 274.
```

I then went to the plugins folder to see what was wrong and saw that the file is named "samparse_tln.pl". I renamed it to "samparse_ltn.pl" and re-ran RegRipper, but encountered the following error:

`Tue May 21 14:03:41 2019: Error in samparse_ltn: Can't locate object method "pluginmain" via package "samparse_ltn" (perhaps you forgot to load "samparse_ltn"?) at C:\Users\<redacted username>\Desktop\Tools\RegRipper\rr.exe line 275.`

I'm not sure what should I do next?

**Comment by keydet89** [comment]
I'm sorry, but I'm not at all sure why you're trying to run 'samparse_ltn" as a plugin.  

The correct spelling is "_tln".  Go back and change the name of the plugin back to what it was before and re-run the command with "samparse_tln".  

Thanks, HTH.

**Comment by dfirnewbie** [comment]
Erm... I didn't try running "samparse_ltn" as a plugin... that was the error returned (Can't locate plugins\samparse_ltn.pl) when parsing the SAM file.

After this first error, I went to the plugins folder to rename samparse_tln.pl to samparse_ltn.pl, but it instead threw another error. I have since renamed it back to samparse_tln.pl, but I'm still facing the first error.

**Comment by keydet89** [comment]
Hhhh...okay, then can you tell me how you were running the plugin?  It would be very helpful if I knew more about how you were trying to run it.

Thanks.

**Comment by dfirnewbie** [comment]
I'm running via rr.exe

1. Load the SAM hive
2. For Profile, I selected "SAM"
3. Press "Rip It"

**Comment by randomaccess3** [comment]
Couple quick questions
1. Did you download the current version from github?
2. can you check the "SAM" profile in the "plugins" directory and check that the spelling is correct for the plugin, if i recall a while back the profile had the incorrect spelling

then lastly try running it from the command line
rip.exe -r SAM -p samparse_tln

**Comment by keydet89** [comment]
dfirnewbie,

I honestly cannot see where you're seeing the plugin spelled "samparse_ltn".  I just checked the profile, and it's spelled correctly there.  It's also spelled correctly in the plugin itself.  

All I can think at this point is that someone misspelled the plugin name somewhere along the line after RR was downloaded.
