### ISSUE TITLE
TSV output - I'm not an idiot, right?

### ISSUE THREAD

**Issue by mike-bailey** [keydet89/RegRipper2.8#53]
First of all thank you for your DFIR contributions - Regripper and otherwise. I’m looking to fork regripper and have it output TSVs. My understanding is I should probably modify rptMsg to write to file (or each invocation will have like 10+ different TSV formats dumping to stdout) and the plugins that call it to have TSV-compatible output? I intend to hopefully open source (doing this outside my work capacity), I just ask because I want to make sure I’m not missing a flag or something else ridiculously easy.

**Comment by keydet89** [comment]
Yeah, you got it...that's about it.  You can have ::rptMsg() write to a file, if you want, or you can have it write to STDOUT like it already does, and simply redirect to a file.

**Comment by mike-bailey** [comment]
Thanks. One of the things that scares me the most about undertaking an hour-burning OSS project  is finding out that it already exists, so glad to hear back so quickly 😄  thank you.

**Comment by keydet89** [comment]
I hear ya...glad to help.  Let me know how it goes.
