### ISSUE TITLE
Services plugin

### ISSUE THREAD

**Issue by azeeee** [keydet89/RegRipper2.8#55]
Comparing the results of the services plugin on Windows 7 systems to Windows 10 systems, I have noticed that on Windows 10 systems a good portion of the services output seems to be off by one line while all the services parse correctly on Windows 7 systems. What I mean by that is that the Display info ends up on the ImagePath line, the ImagePath info ends up on the Type line, the Type info ends up on the Start line, and so on.

**Comment by keydet89** [comment]
Do you have data that you can share?  I'm not seeing this, nor am I able to replicate it.

**Comment by azeeee** [comment]
I will send you an email.
