### ISSUE TITLE
Plugin directory error

### ISSUE THREAD

**Issue by nov3mb3r** [keydet89/RegRipper2.8#57]
Upon executing rip.pl, it appears that it works, but when I execute rip.pl, I get the following error.
```
/ # rip.pl -l
Could not open plugins: No such file or directory
```
This is part of my Dockerfile
```
 && cd /tmp \
  && wget http://www.cpan.org/src/5.0/perl-5.24.0.tar.gz \
  && tar xvzf perl-5.24.0.tar.gz \
  && cd perl-5.24.0 \
  && ./Configure -des && make && make install \
  && cd /tmp && rm -rf perl-5.24.0* \
  && cd /usr/local/bin \
  && wget https://cpanmin.us/ -O cpanm \
  && chmod +x cpanm \
  && cd / \

  #prepare reg
  && mkdir /usr/local/lib/rip-lib \
  && cpanm -l /usr/local/lib/rip-lib Parse::Win32Registry \

  #rr download, mod & installation
  && git clone https://github.com/keydet89/RegRipper2.8.git \ 
  && cd RegRipper2.8 \
  && tail -n +2 rip.pl > rip \
  && perl -pi -e 'tr[\r][]d' rip \
  && sed -i "1i #!`which perl`" rip \
  && sed -i '2i use lib qw(/usr/local/lib/rip-lib/lib/perl5/);' rip \
  && cp rip /usr/local/bin/rip.pl \
  && chmod +x /usr/local/bin/rip.pl \
  && mkdir /usr/local/bin/plugins \
  && cp plugins/* /usr/local/bin/plugins \
  && chmod -R 644 /usr/local/bin/plugins \
  && cd /
```
Now as far as I understand, the issue must be the place where rip.pl is looking for the plugins. Where should I put them?

**Comment by keydet89** [comment]
I'm not sure I can help, as I'm not seeing where there's an error.  However, since you're using Docker:

https://github.com/security-dockerfiles/regripper
https://github.com/phocean/dockerfile-regripper/tree/master
https://hub.docker.com/r/ilyaglow/regripper/dockerfile

**Comment by aapo** [comment]
I didn't test with docker, but seems that running rip.pl from other directory fails to load plugins. With this modification I can put regripper some where and run it from any where:

    cd /tmp
    git clone https://github.com/keydet89/RegRipper2.8.git
    #-> commit: 4cb4ea5af43639563db1fb101f4b0a88975abb6e
    cd RegRipper2.8
    
    tail -n +2 rip.pl > rip
    sed -i "1i #\!`which perl`" rip
    
    sed -i '2i use FindBin qw($Bin);' rip
    sed -i '3i use lib "$Bin";' rip
    sed -i 's=catfile("plugins")=catfile($Bin, "/plugins")=g' rip
    
    mv rip rip.pl
    chmod a+x rip.pl

And testing:

    cd ~
    /tmp/RegRipper2.8/rip.pl -l
    #works
Or

    cd ~
    PATH=$PATH:/tmp/RegRipper2.8/
    rip.pl -l
    #works
