### ISSUE TITLE
[Bug] inprocserver.pl - Lurk detection may generate false positive findings

### ISSUE THREAD

**Issue by jeFF0Falltrades** [keydet89/RegRipper2.8#59]
In `RegRipper2.8/plugins/inprocserver.pl`, the code for detecting a Lurk infection:

```
#Check for Lurk infection (see Dell SecureWorks ref link)					
if ($name eq "{A3CCEDF7-2DE2-11D0-86F4-00A0C913F750}" || $name eq "{a3ccedf7-2de2-11d0-86f4-00a0c913f750}") {
    
    my $l = $s->get_subkey("InprocServer32")->get_value("")->get_data();
    $l =~ tr/[A-Z]/[a-z]/;
    if ($l eq "c:\\windows\\system32\\pngfilt\.dll" || $l eq "c:\\windows\\syswow64\\pngfilt\.dll") {
        ::rptMsg("Possible Lurk infection found!");
        ::rptMsg("  ".$l);
    }
}

eval {
    my $n = $s->get_subkey("InprocServer32")->get_value("")->get_data();
    alertCheckPath($n);
};
```

appears to check if the registry key

`HKEY_CURRENT_USER\ SOFTWARE\Classes\CLSID\{A3CCEDF7-2DE2-11D0-86F4-00A0C913F750}\InProcServer32`

is set to a path pointing to the *pngfilt.dll* library, and if it is, RegRipper displays a message saying that there is a possible Lurk infection.

But according to the [cited analysis on Lurk from SecureWorks](https://www.secureworks.com/research/malware-analysis-of-the-lurk-downloader), this key would be set to a .tmp file in the *%TEMP%* dir if the system is actually infected by Lurk.

It's possible I may be misunderstanding something in the code, but reading the SecureWorks report, I believe this check should instead be looking to see if this registry key is set to anything **other** than the path to *pngfilt.dll*. From what I have been able to find online, this registry key should be set to a path to *pngfilt.dll*, the legitimate library which Lurk attempts to abuse. 

The SecureWorks appendix is a bit confusing as they only list the registry key itself as an IoC, not the actual value of the key, which factors into the detection of Lurk.

**Comment by jeFF0Falltrades** [comment]
![reg](https://user-images.githubusercontent.com/8444166/70378807-ace40b80-18f2-11ea-90bb-5e524b59dc1a.jpg)

^^ Image of a clean Windows machine's registry pointing to *pngfilt.dll* by default.

**Comment by keydet89** [comment]
Okay, noted...thanks.  I'll take a look and see about making the change.
