### ISSUE TITLE
samparse_tln.pl

### ISSUE THREAD

**Issue by vegeta2206** [keydet89/RegRipper2.8#62]
The plugin seems to be unable to collecte timestamp value with :

$c_date = $create->get_timestamp(); at line number ~99

To check this, i put some print lines like 👍 
                                                my $create_path = $key_path."\\Names\\".$v_val{name};
 98                                                 print "### create_path = $create_path ###\n";
 99                                                 if (my $create = $root_key->get_subkey($create_path)) {
100                                                         $c_date = $create->get_timestamp();
101                                                         print "FOUND #### create var $create ####\n";
102                                                         print "FOUND #### c_date var $c_date ####\n";
103                                                         print var_dump($c_date);
104                                                 } else {
105                                                         print "MISSING #### create var $create ####\n";
106                                                 }
107                                         };

command output ( /RegRipper2.8/rip.pl -r sam.reg -p samparse_tln)   

Launching samparse_tln v.20120827
### create_path = SAM\Domains\Account\Users\Names\Administrator ###
FOUND #### create var Parse::Win32Registry::WinNT::Key=HASH(0x197e1d0) ####
FOUND #### c_date var  ####

Any idea before debugging get_timestamp method ?

Thanks a lot for your great job !

**Comment by keydet89** [comment]
Thanks, this was fixed on 4 Jan 2020...I'm not sure if you're using the EXE versions of the tools, but check the READ.ME for notes.  

Thanks!
