### ISSUE TITLE
Can't locate Parse/Win32Registry.pm

### ISSUE THREAD

**Issue by EngBadr** [keydet89/RegRipper2.8#63]
Hello , 
I really think this tool will be very helpful, but it is very hard to install it. any help regarding this issue  
`root@kali:/tmp/RegRipper2.8# rip.pl
Can't locate Parse/Win32Registry.pm in @INC (you may need to install the Parse::Win32Registry module) (@INC contains: /tmp/RegRipper2.8 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /tmp/RegRipper2.8/rip.pl line 31.
BEGIN failed--compilation aborted at /tmp/RegRipper2.8/rip.pl line 31.
`
kali  2020.1b
Thank you

**Comment by keydet89** [comment]
I'm not sure what the issue is, as RegRipper appears to already be installed on Kali:

https://tools.kali.org/forensics/regripper

Googling showed me this:

https://installlion.com/kali/kali/main/r/regripper/install/index.html

**Comment by EngBadr** [comment]
Hello, Thanks for replay 
I believe that this can be installed through 
apt install regripper
for GUI based is working fine 
I'am asking about the text-based version 
rip.pl for text-based version not working 

thank you

**Comment by EngBadr** [comment]
Hello , 
I solve many issues the GUI is working , however, there is issue in time 00:00:00 1970 (UTC) 

I tried to use the text based , but many errors related to plugins not solved
when I run 
rip.pl -l it shows many lines of this

`
Error: Can't locate plugins/networklist.pl in @INC (@INC contains: /opt/regripper/lib/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /opt/regripper/lib/lib/perl5/5.30.0 /opt/regripper/lib/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/rip.pl line 98.

Error: Can't locate plugins/producttype.pl in @INC (@INC contains: /opt/regripper/lib/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /opt/regripper/lib/lib/perl5/5.30.0 /opt/regripper/lib/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/rip.pl line 98.

Error: Can't locate plugins/tracing_tln.pl in @INC (@INC contains: /opt/regripper/lib/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /opt/regripper/lib/lib/perl5/5.30.0 /opt/regripper/lib/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/rip.pl line 98.

Error: Can't locate plugins/auditpol.pl in @INC (@INC contains: /opt/regripper/lib/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /opt/regripper/lib/lib/perl5/5.30.0 /opt/regripper/lib/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/rip.pl line 98.

Error: Can't locate plugins/findexes.pl in @INC (@INC contains: /opt/regripper/lib/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /opt/regripper/lib/lib/perl5/5.30.0 /opt/regripper/lib/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/rip.pl line 98.

Error: Can't locate plugins/amcache_tln.pl in @INC (@INC contains: /opt/regripper/lib/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /opt/regripper/lib/lib/perl5/5.30.0 /opt/regripper/lib/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/rip.pl line 98.

Error: Can't locate plugins/at.pl in @INC (@INC contains: /opt/regripper/lib/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /opt/regripper/lib/lib/perl5/5.30.0 /opt/regripper/lib/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/rip.pl line 98.

Error: Can't locate plugins/trustrecords_tln.pl in @INC (@INC contains: /opt/regripper/lib/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /opt/regripper/lib/lib/perl5/5.30.0 /opt/regripper/lib/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/rip.pl line 98.
`

**Comment by keydet89** [comment]
>...there is issue in time 00:00:00 1970 (UTC)

Yes, please read the readme.md file.

> Error: Can't locate plugins/...

Looks like a path issue.  Try whatever you did to get the GUI to work.

**Comment by EngBadr** [comment]
Hello , Thank you for replay 
Here my recent files , Is this the expected location for Base and other pm files ? 
I moved the files to the mentioned /Parse directory as the following 

root@kali:/usr/share/perl/5.30/Parse/Win32Registry# ls -la
total 116
drwxr-xr-x 4 root root  4096 Apr  5 17:44 .
drwxr-xr-x 4 root root  4096 Apr  5 14:37 ..
-r--r--r-- 1 root root 27313 Apr  5 14:36 Base_old.pm
-rw-r--r-- 1 root root 27535 Apr  5 17:44 Base.pm
-r--r--r-- 1 root root  3131 Apr  5 14:36 Entry.pm
-r--r--r-- 1 root root  9040 Apr  5 17:45 File.pm
-r--r--r-- 1 root root  6300 Apr  5 14:36 Key_old.pm
-rw-r--r-- 1 root root 13693 Apr  5 17:44 Key.pm
-r--r--r-- 1 root root  1974 Apr  5 14:36 Value.pm
drwxr-xr-x 2 root root  4096 Apr  5 14:36 Win95
drwxr-xr-x 2 root root  4096 Apr  5 18:02 WinNT

Is there any advise 

Thank you

**Comment by keydet89** [comment]
> Is there any advise

I'm sorry, I'm not sure what you're asking for...
