### ISSUE TITLE
RegRipper doesn't output ISO 8601 dates YYYY-MM-DD HH:MM:SS 

### ISSUE THREAD

**Issue by globeone** [keydet89/RegRipper2.8#65]
The forensics program Autopsy integrates RegRipper. During a bug solution we discovered that RegRiper is not following the International ISO 8601 standard date format, but is set to Locale.US. This causes problems for anyone who is using RegRipper outside the United States. 

Using standardized dates in ISO 8601 format allows for the easy sorting of date records and less confusion.
YYYY-MM-DD HH:MM:SS

The bug in Autopsy where this was discovered
https://github.com/sleuthkit/autopsy/pull/5827

Link to the International standard date format
https://en.wikipedia.org/wiki/ISO_8601

Please consider changing the date format to the International worldwide standard format. Thanks

**Comment by keydet89** [comment]
The current distro of RegRipper has 389 plugins...that's a lot of plugins that need to be modified.  Since you're asking me to do this, I can't promise that it'll be completed any time soon.
