### ISSUE TITLE
Comdlg32 plugin output

### ISSUE THREAD

**Issue by randomaccess3** [keydet89/RegRipper2.8#8]
I have noticed that occasionally the comdlg32 plugin will output "Libraries" for the OpenSavePidMRU subkey. Some testing has shown that this will occur when a user opens or saves a file in a directory through the "Libraries" section of the navigation pane. An examination of the data using a registry viewer has shown that the full path of the file exists. I can send a sample NTUSER.dat file should you require test data.

I attempted to correct the plugin however have been unsuccessful; it appears that additional code needs to be placed in the parseSystemFolderEntry subroutine.

This issue was previously posted here: https://code.google.com/p/regripper/issues/detail?id=7

**Comment by keydet89** [comment]
> I can send a sample NTUSER.dat file should you require test data. Honestly, I'm not sure what you would expect from me without sample data.
------------------------------------------
Harlan Carvey
"Windows Forensic Analysis"
http://windowsir.blogspot.com
------------------------------------------
