### ISSUE TITLE
Can't call method "get_root_key" on an undefined value

### ISSUE THREAD

**Issue by chiun149** [keydet89/RegRipper2.8#9]
Hello

I'm getting an error (Can't call method "get_root_key" on an undefined value). After downloading the latest 2.8 zip I extracted the files to a folder C:\RR. I checked to be sure all the files and plugin directory are in the folder. any thoughts would be much appreciated, I'm sure its a simple oversight on my end ( Windows 10, perl is not installed)

Thank you

**Comment by keydet89** [comment]
Honestly, I'm not sure what I can do to help.  You need to run a plugin against a hive file.  What are you doing to run RR?  Can you share the hive file that you're running it against?  

There really isn't much information in your question for me to help you.

**Comment by chiun149** [comment]
Thank you for the quick reply. I think I should try running it against some other registry hives. The ones I have were taken with ftk imager off of a live system. I will be sure to update you on the result.


Bob


By the way, the books are great


________________________________

**Comment by keydet89** [comment]
Bob,

That's not entirely helpful.  Could you tell me more about what you were doing, or attempting to do, when you receive the error?  

Also, have you tried opening the hive file in a hex editor to ensure that it was a correctly-structured file?

**Comment by chiun149** [comment]
Harlan

It’s always the basics, I checked the image, ftk imager couldn’t grab the registry, the hives are zero bytes. Problem solved. Thanks for pointing me in that direction (hex editor was blank)

On a side note, I have versions 3E and 4E of the Windows registry books, any others on the way ?

**Comment by keydet89** [comment]
> ... I have versions 3E and 4E of the Windows registry books, any others on the way ?

You can't have the 3rd and 4th editions of Windows Registry Forensics, because the second edition is coming out in April.  The 3rd and 4th editions haven't been written.

**Comment by chiun149** [comment]
Sorry, Windows Forensic Analysis

**Comment by keydet89** [comment]
Ah, okay...that makes sense now.  I thought maybe someone else had written Registry books that I wasn't aware of.

When you ask "...any others on the way ?", what are you referring to?  What's not in 4E or any of the previous editions that you were expecting?

**Comment by djentjbass** [comment]
Hello, I'm having the same issue. I use the RR GUI on a windows machine to try and read an imported hive. almost every single plugin/script gives the "can't call method: get_root_key" error. I've looked into the scripts, and I think it might be a missing function. Any help is greatly appreciated.

**Comment by djentjbass** [comment]
Also, i think this hive might be in 64 bit. Would that cause any problems?  I only see 32 mentioned in the plugins/scripts. I can only kind of read code, so i'm not second guessing anything just trying to help the trouble shooting.

**Comment by randomaccess3** [comment]
Can you please share the exact regripper commands your running and a screenshot of the output?
Preferably not using the GUI, just the command line and output

**Comment by djentjbass** [comment]
Unfortunately, no screen shots available, but the command i used (from the regripper folder which also houses the hive i'm trying to investigate) was:
rip -r "Workstation Hive.reg" -f baseline
It gave the error:
"PLEASE SEE THE PERL2EXE USER MANUAL UNDER 'Can't locate somemodule.pm in @INK'
FOR AN EXPLANATION OF THE FOLLOWING MESSAGE:
'Can't locate plugins\.pl in @INK (@INK contains: PERL2EXE_STORAGE c:\Tools\RegRipper2.8-master C:\Users\Analyst\Appdata\locale\Temp/p2xtmp-12836) at c:\Tools\RegRipper2.8-master\rip.exe line 132"

Line 132 of that file is:
require $plugin_file;

**Comment by randomaccess3** [comment]
Cool thanks; few questions
Which hive is "Workstation Hive.reg" and how did you obtain it? and;
What plugins are in the profile 'baseline'?

Have you tried to run the perl script instead? I've found that to be more reliable (perl2exe seems to cause issues sometimes)

**Comment by djentjbass** [comment]
"Workstation Hive" is the hive from a host of interest, and it was burned to CD for transfer to my computer for analysis. 

And I thought the profile was the perl script? If not, how do I call it properly via command line?
As far as the origin of the baseline, it's a script in the plugins folder. It is technically baseline.pl.

**Comment by randomaccess3** [comment]
Right. So the reason I ask is that I've only gotten rr to work on hives that i've manually copied out of a forensic image, or live disk using a tool like ftk imager. So if it's from the "reg export" command on a live machine I don't think it works.

So usually I'd expect the hive to be named as it was when it was extracted (maybe with an identifier added to it - ie <IDENTIFIER>_NTUSER.DAT)

regripper is a tool written in perl, and Harlan has compiled it with perl2exe to get rip.exe. I find running rip.pl to be more reliable but it does require you to install the registry parsing dependency. 

You are trying to run a plugin using the profile argument

so you can do: 
rip.exe -r ntuser.dat -p baseline
or 
rip.exe -r ntuser.dat -f ntuser 

I'd highly recommend reading through harlans registry book (2e), as it has a section on regripper.

Alternatively, if you want to avoid typing issues then you can check out the GUI that I made for regripper (which also has dependencies).

**Comment by djentjbass** [comment]
Thanks man! Super helpful. It figures that this program works like this. Oh well. Chalk it up to lessons learned. Once again, thank you so much for the help.

**Comment by cybgit** [comment]
Appreciate this is closed, but i'm having the same issue trying to run this against .reg files exported. It works with NTUSER.DAT file no problem, but whenever i try and run against a HIVE file i get the same error on any plugin:

Two example export and running below. 

C:\Utils\RegRipper2.8-master>reg export HKEY_LOCAL_MACHINE HKLM
The operation completed successfully.

C:\Utils\RegRipper2.8-master>rip.exe -r HKLM -p appcompatcache
Launching appcompatcache v.20180311
appcompatcache v.20180311
(System) Parse files from System hive AppCompatCache

Error in plugins\appcompatcache.pl: Can't call method "get_root_key" on an undefined value at C:\Utils\RegRipper2.8-master/plugins\appcompatcache.pl line 68.

C:\Utils\RegRipper2.8-master>reg export HKEY_LOCAL_MACHINE\SYSTEM HKLM_SYSTEM.reg
The operation completed successfully.

C:\Utils\RegRipper2.8-master>rip.exe -r HKLM_SYSTEM.reg -p appcompatcache
Launching appcompatcache v.20180311
appcompatcache v.20180311
(System) Parse files from System hive AppCompatCache

Error in plugins\appcompatcache.pl: Can't call method "get_root_key" on an undefined value at C:\Utils\RegRipper2.8-master/plugins\appcompatcache.pl line 68.

Rgds

**Comment by ch1sh1rsk1** [comment]
I have the same problem... Any issue???

**Comment by mike-bailey** [comment]
Same issue

**Comment by keydet89** [comment]
"...having the same issue trying to run this against .reg files exported..."

RegRipper *MUST* be run against the raw hive file, it does NOT work when run against a .reg file produced via "reg export".

**Comment by mike-bailey** [comment]
I collect, say, four hives programmatically. It works on three, not the fourth. We don't use reg export to my knowledge.

**Comment by mike-bailey** [comment]
I believe I used forecopy
